
# resume information
resume-index = 434176
seed = 12780879921404174533
rate = 1000      
shard = 1/1
nocapture = servername
nocapture = servername

output-filename = -
output-format = json

adapter = wlp2s0
adapter-ip = 192.168.1.253
adapter-port = 42099-42115
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 1-1024
range = 45.33.32.156
range = 66.102.43.0/24
range = 170.210.180.0/24
range = 206.51.255.0/24
